# Generated by Django 5.2.3 on 2025-06-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
